version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: tourplanner_postgres
    restart: always
    environment:
      POSTGRES_USER: touruser
      POSTGRES_PASSWORD: tourpass
      POSTGRES_DB: tourplanner
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
